### ISSUE TITLE
[Bug]: Placing Oven Crashes Game 

### ISSUE THREAD

**Issue by LeavesOfJupiter** [terrarium-earth/Handcrafted#120]
### Bug Description

Attempting to place an oven crashes both single and multiplayer servers. It results in this error:
`[Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalStateException: Invalid block entity handcrafted:oven //`

Bug does not appear to affect other items. It effects both singleplayer and multiplayer

### How to Reproduce?

1. Install latest fabric on client (0.102.1+1.21.1)
2. Install Handcrafted 4.02
3. Run game and open world
4. Craft or somehow acquire oven block
5. Attempt to place block
6. Switch to console after game crash

### Expected Behavior

Expected behavior was for block to place. 

### Version

4.0.2

### Mod Loader Version

0.102+1.21.1

### Mod Loader

Fabric

### Logs or additional context

Appears to use exit 255 specifically when attempting to render block. Below is the full log

`[12:56:42] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalStateException: Invalid block entity handcrafted:oven // earth.terrarium.handcrafted.common.blockentities.OvenBlockEntity state at class_2338{x=-37, y=125, z=53}, got Block{handcrafted:oven}[facing=west,lit=false]
	at net.minecraft.class_2586.method_61175(class_2586.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.<init>(class_2586.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_2624.<init>(class_2624.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_2609.<init>(class_2609.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_3723.<init>(class_3723.java:14) ~[client-intermediary.jar:?]
	at earth.terrarium.handcrafted.common.blockentities.OvenBlockEntity.<init>(OvenBlockEntity.java:12) ~[handcrafted-fabric-1.21.1-4.0.2.jar:?]
	at earth.terrarium.handcrafted.common.blocks.misc.OvenBlock.method_10123(OvenBlock.java:21) ~[handcrafted-fabric-1.21.1-4.0.2.jar:?]
	at net.minecraft.class_2818.method_12010(class_2818.java:286) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_30092(class_1937.java:232) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_30092(class_638.java:160) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8652(class_1937.java:217) ~[client-intermediary.jar:?]
	at net.minecraft.class_1747.method_7708(class_1747.java:153) ~[client-intermediary.jar:?]
	at net.minecraft.class_1747.method_7712(class_1747.java:76) ~[client-intermediary.jar:?]
	at net.minecraft.class_1747.method_7884(class_1747.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.method_7981(class_1799.java:373) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41934(class_636.java:363) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41933(class_636.java:318) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41931(class_636.java:279) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_2896(class_636.java:317) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1583(class_310.java:1852) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:2111) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1938) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1246) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]`

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by tylacine** [comment]
This is also an issue I am having. My crash log if it's any help 
[crash-2024-08-26_22.54.33-client.txt](https://github.com/user-attachments/files/16757308/crash-2024-08-26_22.54.33-client.txt)

**Comment by Istealideas** [comment]
yeah its also happening to me too

**Comment by Shad0wMana** [comment]
I'm having this issue as of the day I'm writing this. I've also confirmed I don't have optifine and I've compared my log with yours and its the same

**Comment by chimericdream** [comment]
I came across this issue after running into the same error message in my own mod. It appears that Mojang added some block entity validation in 1.21.1 that essentially required me to create my own copy of the vanilla one I was using. In my case, it was a barrel, but I suspect the same fix will apply here. The down side is the fact that any blocks previously placed will need to be broken and placed again. There might be a better solution involving mixins or something, but I'm not sure.

**Comment by willogeny** [comment]
I just encountered this exact same issue with the oven. I am playing in a modded 1.21.1 server and the oven crashes the game. The server continued to function but gave this message:

```
[20:08:50] [Netty Server IO #8/ERROR]: Exception occurred in netty pipeline
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401) ~[?:?]
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434) ~[?:?]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:254) ~[netty-buffer-4.1.97.Final.jar:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.97.Final.jar:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by fakedavidgray** [comment]
> I came across this issue after running into the same error message in my own mod. It appears that Mojang added some block entity validation in 1.21.1 that essentially required me to create my own copy of the vanilla one I was using. 

In my case it's the oven in the Handcrafted mod causing the crash. Are we any closer to figuring out a resolution?

**Comment by Nickakanickiam** [comment]
I as well have faced the bug. Minecraft 1.21.1

```
[02:47:09] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalStateException: Invalid block entity handcrafted:oven // earth.terrarium.handcrafted.common.blockentities.OvenBlockEntity state at class_2338{x=-1286, y=97, z=-552}, got Block{handcrafted:oven}[facing=east,lit=false]
	at knot/net.minecraft.class_2586.method_61175(class_2586.java:57) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2586.<init>(class_2586.java:51) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2624.<init>(class_2624.java:33) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2609.<init>(class_2609.java:132) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3723.<init>(class_3723.java:14) ~[client-intermediary.jar:?]
	at knot/earth.terrarium.handcrafted.common.blockentities.OvenBlockEntity.<init>(OvenBlockEntity.java:12) ~[handcrafted-fabric-1.21.1-4.0.2.jar:?]
	at knot/earth.terrarium.handcrafted.common.blocks.misc.OvenBlock.method_10123(OvenBlock.java:21) ~[handcrafted-fabric-1.21.1-4.0.2.jar:?]
	at knot/net.minecraft.class_2818.redirect$dne000$lithium$createBlockEntityWithCachedStateFix(class_2818.java:3757) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2818.method_12010(class_2818.java:286) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1937.method_30092(class_1937.java:232) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_638.method_30092(class_638.java:160) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1937.method_8652(class_1937.java:217) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1747.method_7708(class_1747.java:153) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1747.method_7712(class_1747.java:76) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1747.method_7884(class_1747.java:46) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1799.method_7981(class_1799.java:373) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_636.method_41934(class_636.java:366) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_636.method_41933(class_636.java:318) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_636.method_41931(class_636.java:279) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_636.method_2896(class_636.java:317) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1583(class_310.java:1852) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1508(class_310.java:2111) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1574(class_310.java:1938) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1246) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
```

**Comment by Bruhnanza** [comment]
I have also faced this issue Fabric 1.21.1 Handcrafted 4.0.2
```
Description: Unexpected error
java.lang.IllegalStateException: Invalid block entity handcrafted:oven // earth.terrarium.handcrafted.common.blockentities.OvenBlockEntity state at class_2338{x=-667, y=77, z=-150}, got Block{handcrafted:oven}[facing=north,lit=false]
	at knot//net.minecraft.class_2586.method_61175(class_2586.java:57)
	at knot//net.minecraft.class_2586.<init>(class_2586.java:51)
	at knot//net.minecraft.class_2624.<init>(class_2624.java:33)
	at knot//net.minecraft.class_2609.<init>(class_2609.java:132)
	at knot//net.minecraft.class_3723.<init>(class_3723.java:14)
	at knot//earth.terrarium.handcrafted.common.blockentities.OvenBlockEntity.<init>(OvenBlockEntity.java:12)
	at knot//earth.terrarium.handcrafted.common.blocks.misc.OvenBlock.method_10123(OvenBlock.java:21)
	at knot//net.minecraft.class_2818.redirect$fka000$lithium$createBlockEntityWithCachedStateFix(class_2818.java:4757)
	at knot//net.minecraft.class_2818.method_12010(class_2818.java:286)
	at knot//net.minecraft.class_1937.method_30092(class_1937.java:232)
	at knot//net.minecraft.class_638.method_30092(class_638.java:160)
	at knot//net.minecraft.class_1937.method_8652(class_1937.java:217)
	at knot//net.minecraft.class_1747.method_7708(class_1747.java:153)
	at knot//net.minecraft.class_1747.method_7712(class_1747.java:76)
	at knot//net.minecraft.class_1747.mixinextras$bridge$method_7712$27(class_1747.java)
	at knot//net.minecraft.class_1747.wrapOperation$hjh000$snowrealmagic$srm_useOn(class_1747.java:1544)
	at knot//net.minecraft.class_1747.method_7884(class_1747.java:46)
	at knot//net.minecraft.class_1799.method_7981(class_1799.java:373)
	at knot//net.minecraft.class_636.method_41934(class_636.java:363)
	at knot//net.minecraft.class_636.method_41933(class_636.java:318)
	at knot//net.minecraft.class_636.method_41931(class_636.java:279)
	at knot//net.minecraft.class_636.method_2896(class_636.java:317)
	at knot//net.minecraft.class_310.method_1583(class_310.java:1852)
	at knot//net.minecraft.class_310.redirect$bel000$betterthirdperson$onDoItemUse(class_310.java:7234)
	at knot//net.minecraft.class_310.method_1508(class_310.java:2111)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1938)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1246)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by Nangt3c** [comment]
Same issue here, it also happens when placing specific blocks from another mod called Deeper and Darker. So as the other user said before, Mojang changed something with how the game renders blocks.

`---- Minecraft Crash Report ----
// Don't do that.

Time: 2025-01-06 20:51:39
Description: Unexpected error

java.lang.IllegalStateException: Invalid block entity handcrafted:oven // earth.terrarium.handcrafted.common.blockentities.OvenBlockEntity state at class_2338{x=-5, y=-60, z=13}, got Block{handcrafted:oven}[facing=south,lit=false]
	at knot//net.minecraft.class_2586.method_61175(class_2586.java:57)
	at knot//net.minecraft.class_2586.<init>(class_2586.java:51)
	at knot//net.minecraft.class_2624.<init>(class_2624.java:33)
	at knot//net.minecraft.class_2609.<init>(class_2609.java:132)
	at knot//net.minecraft.class_3723.<init>(class_3723.java:14)
	at knot//earth.terrarium.handcrafted.common.blockentities.OvenBlockEntity.<init>(OvenBlockEntity.java:12)
	at knot//earth.terrarium.handcrafted.common.blocks.misc.OvenBlock.method_10123(OvenBlock.java:21)
	at knot//net.minecraft.class_2818.redirect$ddl000$lithium$createBlockEntityWithCachedStateFix(class_2818.java:4257)
	at knot//net.minecraft.class_2818.method_12010(class_2818.java:286)
	at knot//net.minecraft.class_1937.method_30092(class_1937.java:232)
	at knot//net.minecraft.class_638.method_30092(class_638.java:160)
	at knot//net.minecraft.class_1937.method_8652(class_1937.java:217)
	at knot//net.minecraft.class_1747.method_7708(class_1747.java:153)
	at knot//net.minecraft.class_1747.method_7712(class_1747.java:76)
	at knot//net.minecraft.class_1747.method_7884(class_1747.java:46)
	at knot//net.minecraft.class_1799.method_7981(class_1799.java:373)
	at knot//net.minecraft.class_636.method_41934(class_636.java:363)
	at knot//net.minecraft.class_636.method_41933(class_636.java:318)
	at knot//net.minecraft.class_636.method_41931(class_636.java:279)
	at knot//net.minecraft.class_636.method_2896(class_636.java:317)
	at knot//net.minecraft.class_310.method_1583(class_310.java:1852)
	at knot//net.minecraft.class_310.method_1508(class_310.java:2111)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1938)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1246)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)`

**Comment by MkGrinngo** [comment]
I, too, am running into this issue. Client-side crash. Server's fine.

```
Time: 2025-02-10 21:50:17
Description: Unexpected error

java.lang.IllegalStateException: Invalid block entity handcrafted:oven // earth.terrarium.handcrafted.common.blockentities.OvenBlockEntity state at class_2338{x=188, y=76, z=-341}, got Block{handcrafted:oven}[facing=north,lit=false]
	at knot//net.minecraft.class_2586.method_61175(class_2586.java:57)
	at knot//net.minecraft.class_2586.<init>(class_2586.java:51)
	at knot//net.minecraft.class_2624.<init>(class_2624.java:33)
	at knot//net.minecraft.class_2609.<init>(class_2609.java:132)
	at knot//net.minecraft.class_3723.<init>(class_3723.java:14)
	at knot//earth.terrarium.handcrafted.common.blockentities.OvenBlockEntity.<init>(OvenBlockEntity.java:12)
	at knot//earth.terrarium.handcrafted.common.blocks.misc.OvenBlock.method_10123(OvenBlock.java:21)
	at knot//net.minecraft.class_2818.redirect$fmg000$lithium$createBlockEntityWithCachedStateFix(class_2818.java:4757)
	at knot//net.minecraft.class_2818.method_12010(class_2818.java:286)
	at knot//net.minecraft.class_1937.method_30092(class_1937.java:232)
	at knot//net.minecraft.class_638.method_30092(class_638.java:160)
	at knot//net.minecraft.class_1937.method_8652(class_1937.java:217)
	at knot//net.minecraft.class_1747.method_7708(class_1747.java:153)
	at knot//net.minecraft.class_1747.method_7712(class_1747.java:76)
	at knot//net.minecraft.class_1747.method_7884(class_1747.java:46)
	at knot//net.minecraft.class_1799.method_7981(class_1799.java:373)
	at knot//net.minecraft.class_636.method_41934(class_636.java:363)
	at knot//net.minecraft.class_636.method_41933(class_636.java:318)
	at knot//net.minecraft.class_636.method_41931(class_636.java:279)
	at knot//net.minecraft.class_636.method_2896(class_636.java:317)
	at knot//net.minecraft.class_310.method_1583(class_310.java:1852)
	at knot//net.minecraft.class_310.method_1508(class_310.java:2111)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1938)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1246)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by hhenry12** [comment]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2025-03-16 12:08:10
Description: Unexpected error

java.lang.IllegalStateException: Invalid block entity handcrafted:oven // earth.terrarium.handcrafted.common.blockentities.OvenBlockEntity state at class_2338{x=-969, y=66, z=1401}, got Block{handcrafted:oven}[facing=north,lit=false]
	at knot//net.minecraft.class_2586.method_61175(class_2586.java:57)
	at knot//net.minecraft.class_2586.<init>(class_2586.java:51)
	at knot//net.minecraft.class_2624.<init>(class_2624.java:33)
	at knot//net.minecraft.class_2609.<init>(class_2609.java:132)
	at knot//net.minecraft.class_3723.<init>(class_3723.java:14)
	at knot//earth.terrarium.handcrafted.common.blockentities.OvenBlockEntity.<init>(OvenBlockEntity.java:12)
	at knot//earth.terrarium.handcrafted.common.blocks.misc.OvenBlock.method_10123(OvenBlock.java:21)
	at knot//net.minecraft.class_2818.redirect$cih000$lithium$createBlockEntityWithCachedStateFix(class_2818.java:3260)
	at knot//net.minecraft.class_2818.method_12010(class_2818.java:286)
	at knot//net.minecraft.class_1937.method_30092(class_1937.java:232)
	at knot//net.minecraft.class_638.method_30092(class_638.java:160)
	at knot//net.minecraft.class_1937.method_8652(class_1937.java:217)
	at knot//net.minecraft.class_1747.method_7708(class_1747.java:153)
	at knot//net.minecraft.class_1747.method_7712(class_1747.java:76)
	at knot//net.minecraft.class_1747.method_7884(class_1747.java:46)
	at knot//net.minecraft.class_1799.method_7981(class_1799.java:373)
	at knot//net.minecraft.class_636.method_41934(class_636.java:366)
	at knot//net.minecraft.class_636.method_41933(class_636.java:318)
	at knot//net.minecraft.class_636.method_41931(class_636.java:279)
	at knot//net.minecraft.class_636.method_2896(class_636.java:317)
	at knot//net.minecraft.class_310.method_1583(class_310.java:1852)
	at knot//net.minecraft.class_310.redirect$zek000$betterthirdperson$onDoItemUse(class_310.java:5734)
	at knot//net.minecraft.class_310.method_1508(class_310.java:2111)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1938)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1246)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
