### ISSUE TITLE
[Bug]: Crash with latest version handcrafted-fabric-1.19.3-2.1.0

### ISSUE THREAD

**Issue by gamerpotion** [terrarium-earth/Handcrafted#19]
### Bug Description

Hi, am using this in my modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg

After upgrading to the latest version and logging onto server, it crashes with the following.

```---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-03-14 01:28:49
Description: Unexpected error

java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.class_4587.method_22903(class_4587.java:56)
	at net.minecraft.class_761.method_22710(class_761.java:1340)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.class_4587.method_22903(class_4587.java:56)
	at net.minecraft.class_761.method_22710(class_761.java:1340)
	at net.minecraft.class_757.method_3188(class_757.java:1085)

-- Affected level --
Details:
	All players: 1 total; [class_746['JDKun11'/247900, l='ClientLevel', x=-849.50, y=72.94, z=5978.50]]
	Chunk stats: 74, 74
	Level dimension: minecraft:overworld
	Level spawn location: World: (-850,100,5978), Section: (at 14,4,10 in -54,6,373; chunk contains blocks -864,-64,5968 to -849,319,5983), Region: (-2,11; contains chunks -64,352 to -33,383, blocks -1024,-64,5632 to -513,319,6143)
	Level time: 27695224 game time, 447566 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)```

### How to Reproduce?

_No response_

### Expected Behavior

_No response_

### Version

handcrafted-fabric-1.19.3-2.1.0

### Mod Loader Version

1.19.3

### Mod Loader

Fabric

### Logs or additional context

_No response_

**Comment by AlexNijjar** [comment]
fixed in c86381d
